### PR TITLE
Fix #35 - Support nonescaping closure parameters

### LINKED ISSUE #35: Support `func foo(nonescapingClosure: () -> Void)`
Thanks for the work you've done on this library! As someone who loves Sourcery mocks, it's no surprise someone would take advantage of Swift Macros to reimplement that functionality, so thanks for being that person!

Anywhoo, this is from the `main` branch as of today.

functions with nonescaping closures will cause `Spyable` to fail to compile, whereas escaping closures compile just fine:
Screenshot 2023-09-09 at 5 27 27 PM

As a sidenote, it also seems like indentation is off at lines 9 & 22.

For reference: The code generated in Sourcery's Automockable for the same protocol is this, which compiles:
```swift
class MyProtocolMock: MyProtocol {

    //MARK: - doThing

    var doThingCompletionCallsCount = 0
    var doThingCompletionCalled: Bool {
        return doThingCompletionCallsCount > 0
    }
    var doThingCompletionReceivedCompletion: ((() -> Void))?
    var doThingCompletionReceivedInvocations: [((() -> Void))] = []
    var doThingCompletionClosure: ((@escaping () -> Void) -> Void)?

    func doThing(completion: @escaping () -> Void) {
        doThingCompletionCallsCount += 1
        doThingCompletionReceivedCompletion = completion
        doThingCompletionReceivedInvocations.append(completion)
        doThingCompletionClosure?(completion)
    }

    //MARK: - doThing

    var doThingNonescapingCompletionCallsCount = 0
    var doThingNonescapingCompletionCalled: Bool {
        return doThingNonescapingCompletionCallsCount > 0
    }
    var doThingNonescapingCompletionClosure: ((() -> Void) -> Void)?

    func doThing(nonescapingCompletion: () -> Void) {
        doThingNonescapingCompletionCallsCount += 1
        doThingNonescapingCompletionClosure?(nonescapingCompletion)
    }
}
```
It looks like this could be resolved by making spyable match automockable's behavior by having these two lines be removed for nonescaping closures:
```swift
doThingNonEscapingCompletionReceivedNonEscapingCompletion = (nonEscapingCompletion)
doThingNonEscapingCompletionReceivedInvocations.append((nonEscapingCompletion))
```
 [Automockable.stencil](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoMockable.stencil) has lots of checks that go something like `if x and not hasNonEscapingClosures`, so maybe something similar could be replicated here?

### PR DESCRIPTION
**Pull request by dafurman**
See https://github.com/Matejkob/swift-spyable/issues/35 for a description of the issue that this PR solves.

I also added support for parameters using autoclosure, as I noticed that attempting to use it would lead to a compilation issue:
Screenshot 2023-11-23 at 12 13 08 PM

### CODE REVIEW

File: Sources/SpyableMacro/Extensions/FunctionParameters+Extensions.swift [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    if type.is(FunctionTypeSyntax.self) {
+      return true
+    }
+    guard let attributedType = type.as(AttributedTypeSyntax.self),
+          attributedType.baseType.is(FunctionTypeSyntax.self) else {
+      return false
+    }
+
+    return !attributedType.attributes.contains {
+      $0.attributeNameTextMatches("escaping")
```
Comment (Matejkob) [inline Sources/SpyableMacro/Extensions/FunctionParameters+Extensions.swift:21]: How about instead of using the name of the token throw the string we use `TokenSyntax.keyword.text`?
```suggestion
      $0.attributeNameTextMatches(TokenSyntax.keyword(.escaping).text)
```

File: Sources/SpyableMacro/Extensions/FunctionParameters+Extensions.swift [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    }
+  }
+
+  var usesAutoclosure: Bool {
+    type.as(AttributedTypeSyntax.self)?.attributes.contains {
+      $0.attributeNameTextMatches("autoclosure")
```
Comment (Matejkob) [inline Sources/SpyableMacro/Extensions/FunctionParameters+Extensions.swift:27]: Similar to `escaping` how about: 
```suggestion
      $0.attributeNameTextMatches(TokenSyntax.keyword(.autoclosure).text)
```
?

File: Tests/SpyableMacroTests/Extensions/UT_FunctionParameterListSyntax+Extensions.swift [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+@testable import SpyableMacro
+
+final class UT_FunctionParameterListSyntaxExtensions: XCTestCase {
+  func testSupportsParameterTracking() {
+    XCTAssertTrue(
+      FunctionParameterListSyntax {
+        "param: Int"
+        "param: inout Int"
+        "param: @autoclosure @escaping (Int) throws async -> Void"
```
Comment (Matejkob) [inline Tests/SpyableMacroTests/Extensions/UT_FunctionParameterListSyntax+Extensions.swift:12]: Parser from `swift-syntax` is producing an error here:
Screenshot 2023-12-29 at 8 32 11 PM
This change should fix it:
```suggestion
        "param: @autoclosure @escaping (Int) async throws -> Void"
```

**Review by Matejkob — COMMENTED** [review]
Thank you very much for your contribution! I apologize for the delay in getting this review to you. I plan to allocate more time to this project in the future.

I've left a few inline comments, but they are minor. Overall, your changes look really good to me! Thanks once again for your contribution!

**Comment by Matejkob** [comment]
My last changes resulted in new conflicts in this PR. Here is PR to your fork that solves those conflicts: https://github.com/dafurman/swift-spyable/pull/1

File: Tests/SpyableMacroTests/Extensions/UT_FunctionParameterListSyntax+Extensions.swift (hunk 3 above)
Comment (dafurman) [reply Tests/SpyableMacroTests/Extensions/UT_FunctionParameterListSyntax+Extensions.swift]: I'm actually a little curious what tooling you used to catch this one. Is there a swift-syntax CLI tool that you can run against a project / directory?
It'd be cool to add whatever you did here to catch this to the Github Actions checks!

**Review by Matejkob — APPROVED** [review]
Great work on these changes! I've reviewed the updates and everything looks solid and well-implemented. I appreciate the attention to detail you've included. Thanks! 🙌

File: Tests/SpyableMacroTests/Extensions/UT_FunctionParameterListSyntax+Extensions.swift (hunk 3 above)
Comment (Matejkob) [reply Tests/SpyableMacroTests/Extensions/UT_FunctionParameterListSyntax+Extensions.swift]: I've just run unit tests in Xcode and `swift-syntax` library has logged this error into the console. I'm unsure why it did not throw an error when creating the node. I will investigate it later this week.
