### PR TITLE
Fix to search for 'Spyable' in AttributeListSyntax when checking behindPreprocessorFlag.

### LINKED ISSUE #79: Preprocessor flag can't be retriever when protocol has more then one attribute
**Bug Description:**

When multiple attributes are attached to a protocol, such as `Spyable` and `MainActor`, there is an issue in retrieving `behindPreprocessorFlag` value. 

Consider the following declaration:
```swift
@Spyable(behindPreprocessorFlag: "DEBUG")
protocol Foo {}
```
In this scenario, we can successfully retrieve the value of `behindPreprocessorFlag` because `Spyable` is the only attribute. However, if we add an additional attribute as shown below:
```diff
+@MainActor
@Spyable(behindPreprocessorFlag: "DEBUG")
protocol Foo {}
```
The retrieval of the `Spyable` attribute's value becomes problematic. The current implementation only considers the first attribute attached to the protocol declaration. Therefore, when `Spyable` is not the first attribute, its values become inaccessible.

**Proposed Solution:** 

To resolve this issue, the approach to attribute retrieval needs modification. Instead of only considering the first attribute, the implementation should search the entire list of attributes for the `Spyable` attribute. This can be accomplished by checking for an `attributeName` that matches `Spyable`.

### PR DESCRIPTION
**Pull request by TTOzzi**
Resolve #79 

Hello 👋
Fix to search for `Spyable` in `AttributeListSyntax` when checking `behindPreprocessorFlag` and add test case.

### CODE REVIEW

File: Sources/SpyableMacro/Macro/SpyableMacro.swift [hunk 1]
```diff
@@ -61,7 +61,11 @@ public enum SpyableMacro: PeerMacro {
 extension DeclSyntaxProtocol {
   /// - Returns: The preprocessor `flag` parameter that can be optionally provided via `@Spyable(flag:)`.
   fileprivate var preprocessorFlag: String? {
-    self.as(ProtocolDeclSyntax.self)?.attributes.first?
+    self
+      .as(ProtocolDeclSyntax.self)?.attributes.first {
```
Comment (TTOzzi) [inline Sources/SpyableMacro/Macro/SpyableMacro.swift:65]: If a newline is not added after `self` the formatting becomes unpretty when running 'make format,' as shown in the attached screenshot, so I added the newline 🤔 
스크린샷 2024-01-27 오전 4 13 51

Comment (Matejkob) [reply Sources/SpyableMacro/Macro/SpyableMacro.swift:65]: That's find, thank you! 🙌

**Review by Matejkob — APPROVED** [review]
Thank you for your contribution! 
Everything looks good! 🙌
